name: Bump tag version

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.35.0
      id: tag
      with:
        fetch-depth: '0'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true   
        DEFAULT_BUMP: patch       
