name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bumb-tag:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Find next tag version
        uses: anothrNick/github-tag-action@1.35.0
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.0.5
          DRY_RUN: true
      - 
        name: prints next version
        run: echo ${{ steps.tag_version.outputs.new_tag}}
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tomso/az-pipeline-container
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          cache: true
          tags: "latest,${{ steps.tag_version.outputs.new_tag }}"
      - 
        name: Update Docker hub description
        uses: peter-evans/dockerhub-description@v2.0.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: tomso/az-pipeline-container
      - 
        name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.tag_version.outputs.new_tag }}"
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}


